# your informations
author:
  name: Bernardo Pacheco
  description:
  picture: /assets/images/avatar.jpg

# site description
description: Thoughts and writings about software engineering by Bernardo Pacheco.

# site url
url: http://bernardopacheco.net

# site title
title: Bernardo Pacheco

# site version
version: 1.0.0

# number of posts per page
paginate: 10

# your github username
github_username: bernardopacheco

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: true
  google_plus: true
  linkedin: true
  disqus: true

# if share.facebook is true, provide your facebook app id
facebook_app_id: 730635297031262

# if you have a Twitter account, provide your twitter username (without the @ character) for a better formatted Twitter Card share
twitter_username: BernardoPachec0

# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: bernardopacheco
disqus_api_key: o2szu05bLNqiXiRvqe2oFvIHYYVR24eVkQiGs5WHcj0VUnvF8GCqD9HQUZErwCe7
disqus_recent_comments_to_display: 5

# google analytics ID
google_analytics_id: UA-58186085-1

markdown: kramdown
highlighter: pygments
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]
excerpt_separator: <!--excerpt_separator-->
